### ISSUE TITLE
Buffer

### ISSUE THREAD

**Issue by svperfecta** [openfaas/nodejs-afterburn#1]
On how we're parsing incoming data.

* This will receive a series of HTTP requests, each with a set of headers and a payload.
* The header will indicate the but length of the payload
* We need to create a buffer for the body, and only dispatch it to the handler when the appropriate number of bytes are received.

Also - handling errors.

**Comment by alexellis** [comment]
I believe this is fixed in #3

**Comment by alexellis** [comment]
Fix confirmed by Brian Guilder on your team @genexp - please feel free to keep commenting re: error handling etc.
