### ISSUE TITLE
Following readme sample results in non-working 502

### ISSUE THREAD

**Issue by rosskevin** [openfaas/nodejs-afterburn#10]
```bash
faas-cli template pull https://github.com/openfaas/nodejs-afterburn
faas-cli new --lang node-afterburn burner

faas-cli build -f burner.yml
faas-cli deploy -f burner.yml
echo test | faas-cli invoke burner
```

I've got other sample functions running such as `nodeinfo`, but this one will not run on command line or via the console.  The invoke button remains greyed out.

This is my first day with OpenFaas and it would be less confusing for this template to work out of the box.

It is unclear to me if this is related to the other open issue about a GET request, but as-is I'm not following how to alter it to make it work or why the invoke button appears disabled.

**Comment by rosskevin** [comment]
So, the above is a result of running on kubernetes, I did not do a `faas-cli push` at any point and inspecting the pods reveal something like:

```
kubectl get pods -n openfaas-fn
NAME                        READY     STATUS             RESTARTS   AGE
foo-66b5b8b487-wsb64        0/1       ImagePullBackOff   0          12m
```

So I either need to get k8s to pull images from local, push to a registry first, or use swarm (because it sees local images).

**Comment by alexellis** [comment]
This is not an issue with the template.

With Kubernetes your images need to be pushed to any registry local or remote. Please go through the OpenFaaS workshop so you can learn the basic workflow for writing functions.

http://github.com/openfaas/workshop
